import Link from "next/link";
import type { Occupation } from "@/types/occupation";
import { ComparisonViewTracker } from "./analytics/AnalyticsTrackers";

// Salary and future demand are absent by design: the Phase 5 engine produces neither and
// they are not fabricated. Evidence-quality metrics take their place.

const metrics: { label: string; key: keyof Occupation; lower?: boolean }[] = [{ label: "AI Exposure", key: "aiExposure", lower: true }, { label: "Replacement Risk", key: "replacementRisk", lower: true }, { label: "Human Dependency", key: "humanDependency" }, { label: "Physical Dependency", key: "physicalDependency" }, { label: "Labour-market Resilience", key: "labourMarketResilience" }, { label: "Confidence", key: "confidence" }, { label: "Task Coverage", key: "weightedTaskCoverage" }];

export function CareerComparison({ a, b }: { a: Occupation; b: Occupation }) { return <article className="card comparison-card"><ComparisonViewTracker slugA={a.slug} slugB={b.slug} /><div className="comparison-head"><CareerHead job={a} /><div className="vs-badge">VS</div><CareerHead job={b} /></div><div className="comparison-table"><div className="comparison-row comparison-labels"><b>Metric</b><b>{a.title}</b><b>{b.title}</b><b>Advantage</b></div>{metrics.map((metric) => { const av = Number(a[metric.key]); const bv = Number(b[metric.key]); const winner = av === bv ? "Even" : metric.lower ? (av < bv ? a.title : b.title) : (av > bv ? a.title : b.title); return <div className="comparison-row" key={metric.label}><strong>{metric.label}</strong><span>{av}</span><span>{bv}</span><b>{winner}</b></div>; })}</div><div className="notice"><strong>Verdict</strong><p>{a.replacementRisk < b.replacementRisk ? a.title : b.title} currently appears more AI-resilient. That advantage reflects lower replacement pressure after human dependency, physical dependency, labour-market resilience and adoption factors are included.</p></div></article>; }
function CareerHead({ job }: { job: Occupation }) { return <div><span className="chip">{job.category}</span><h2>{job.title}</h2><div className="score-number">{job.replacementRisk}<small>/100 risk</small></div><Link className="text-link" href={`/jobs/${job.slug}`}>Full analysis →</Link></div>; }
