"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useState } from "react";
import type { Occupation } from "@/types/occupation";

type Answers = { occupation: string; experience: string; skills: string; education: string; country: string; salary: string; retraining: string };
const steps = ["Current career", "Skills & education", "Goals", "Retraining"];

export function CareerFinderForm({ occupations }: { occupations: Occupation[] }) {
  const router = useRouter(); const params = useSearchParams(); const initialSlug = params.get("occupation");
  const initial = occupations.find((job) => job.slug === initialSlug)?.title ?? occupations[0]?.title ?? "";
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Answers>({ occupation: initial, experience: "4", skills: "", education: "bachelors", country: "India", salary: "same_or_higher", retraining: "few_months" });
  const set = (key: keyof Answers, value: string) => setAnswers((current) => ({ ...current, [key]: value }));
  function submit(event: FormEvent) { event.preventDefault(); if (step < steps.length - 1) return setStep(step + 1); const current = occupations.find((job) => job.title === answers.occupation) ?? occupations[0]; if (!current) return; const query = new URLSearchParams({ from: current.slug, experienceYears: answers.experience, skills: answers.skills, education: answers.education, country: answers.country, salaryExpectation: answers.salary, retrainingTolerance: answers.retraining }); router.push(`/career-finder/results?${query}`); }
  return <div className="finder-shell"><div className="progress-head"><span>Step {step + 1} of {steps.length}</span><strong>{steps[step]}</strong></div><div className="progress-track"><span style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div><form className="card finder-card" onSubmit={submit}>
    {step === 0 && <fieldset><legend>Where are you today?</legend><p>Start with your current role and experience. No account is required.</p><div className="form-grid"><label>Current profession<select value={answers.occupation} onChange={(e) => set("occupation", e.target.value)}>{occupations.map((job) => <option key={job.slug}>{job.title}</option>)}</select></label><label>Years of experience<select value={answers.experience} onChange={(e) => set("experience", e.target.value)}><option value="1">0–2 years</option><option value="4">3–5 years</option><option value="8">6–10 years</option><option value="12">10+ years</option></select></label></div></fieldset>}
    {step === 1 && <fieldset><legend>What do you already bring?</legend><p>We use these details to estimate skill overlap—not to screen you out.</p><div className="form-grid"><label>Education<select value={answers.education} onChange={(e) => set("education", e.target.value)}><option value="high_school">High school</option><option value="diploma">Diploma</option><option value="bachelors">Bachelor&apos;s degree</option><option value="masters">Master&apos;s degree</option><option value="self_taught">Self-taught</option></select></label><label className="full-field">Strongest skills<textarea value={answers.skills} onChange={(e) => set("skills", e.target.value)} rows={4} /></label></div></fieldset>}
    {step === 2 && <fieldset><legend>What should your next move deliver?</legend><p>Location and salary direction help us avoid unrealistic recommendations.</p><div className="form-grid"><label>Country or location<input value={answers.country} onChange={(e) => set("country", e.target.value)} /></label><label>Salary expectation<select value={answers.salary} onChange={(e) => set("salary", e.target.value)}><option value="temporary_decrease">Open to a temporary decrease</option><option value="same_or_higher">Same or higher</option><option value="meaningful_increase">Meaningful increase</option></select></label></div></fieldset>}
    {step === 3 && <fieldset><legend>How much retraining works for you?</legend><p>Choose the furthest transition you would realistically consider.</p><div className="option-grid">{[{ value: "almost_none", title: "Almost none", copy: "A very close adjacent role." }, { value: "few_months", title: "A few months", copy: "A focused set of new skills." }, { value: "six_to_twelve", title: "6–12 months", copy: "A meaningful transition." }, { value: "major_transition", title: "Major transition", copy: "Retrain for a much stronger outcome." }].map((option) => <button type="button" className={answers.retraining === option.value ? "selected" : ""} aria-pressed={answers.retraining === option.value} key={option.value} onClick={() => set("retraining", option.value)}><strong>{option.title}</strong><span>{option.copy}</span></button>)}</div></fieldset>}
    <div className="form-actions"><button className="button secondary" type="button" disabled={step === 0} onClick={() => setStep(Math.max(0, step - 1))}>← Back</button><button className="button" type="submit">{step === steps.length - 1 ? "See my career matches" : "Continue"} →</button></div>
  </form></div>;
}
