-- 028 — Deterministic public occupation content, staged.
--
-- Nine editorial `occupations` rows exist. A launch cohort needs hundreds. This migration
-- creates a staging namespace for content derived deterministically from O*NET and from
-- promoted scores, so content can be generated, reviewed and corrected before any row
-- reaches the editorial table.
--
-- THE CENTRAL RULE, ENFORCED BY COLUMN SEPARATION
-- -----------------------------------------------
-- `source_*` columns hold O*NET facts, copied verbatim and attributed. `jobsvsai_*` columns
-- hold JobsVsAI interpretation, produced by a versioned template from persisted scores.
-- Nothing in this table is written in prose by a language model, and nothing factual is
-- paraphrased — a paraphrase of an occupation description is an invention with a citation
-- attached to it.
--
-- Related occupations come from `onet_related_occupations`, not from the hand-seeded
-- `career_relationships` graph.

BEGIN;

CREATE TABLE public_occupation_content_runs (
  id BIGSERIAL PRIMARY KEY,
  run_key TEXT NOT NULL UNIQUE,
  content_policy_version TEXT NOT NULL,
  verdict_template_version TEXT NOT NULL,
  triage_run_id BIGINT REFERENCES phase6_launch_triage_runs(id),
  promotion_run_id BIGINT REFERENCES production_promotion_runs(id),
  onet_source_version TEXT NOT NULL,
  occupation_count INTEGER NOT NULL DEFAULT 0 CHECK (occupation_count >= 0),
  complete_count INTEGER NOT NULL DEFAULT 0 CHECK (complete_count >= 0),
  incomplete_count INTEGER NOT NULL DEFAULT 0 CHECK (incomplete_count >= 0),
  input_hash CHAR(64) NOT NULL,
  source_id BIGINT NOT NULL REFERENCES data_sources(id),
  provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (occupation_count = complete_count + incomplete_count)
);

CREATE TABLE public_occupation_content_candidates (
  id BIGSERIAL PRIMARY KEY,
  content_run_id BIGINT NOT NULL REFERENCES public_occupation_content_runs(id),
  identity_id BIGINT NOT NULL REFERENCES canonical_occupation_identities(id),
  onet_soc_code TEXT NOT NULL,

  -- JobsVsAI canonical identity for the page.
  canonical_title TEXT NOT NULL,
  title_source TEXT NOT NULL CHECK (title_source IN ('onet_preferred','jobsvsai_editorial')),
  seo_slug TEXT NOT NULL,
  slug_source TEXT NOT NULL CHECK (slug_source IN ('derived_from_canonical_title','existing_editorial')),

  -- Job family. The SOC major group is a source fact; the label is a JobsVsAI rendering of
  -- it, deterministic and versioned, never a new taxonomy.
  soc_major_group TEXT NOT NULL,
  source_soc_major_group_title TEXT NOT NULL,
  jobsvsai_job_family TEXT NOT NULL,

  -- O*NET facts. Verbatim, attributed, never paraphrased.
  source_summary TEXT,
  source_summary_origin TEXT CHECK (source_summary_origin IN ('onet_occupation_description')),
  source_attribution TEXT NOT NULL,

  -- JobsVsAI interpretation, generated by a versioned template from the promoted snapshot.
  jobsvsai_verdict TEXT,
  verdict_snapshot_id BIGINT REFERENCES production_occupation_score_snapshots(id),
  verdict_inputs JSONB NOT NULL DEFAULT '{}'::jsonb,

  search_aliases TEXT NOT NULL DEFAULT '',
  alternate_title_count INTEGER NOT NULL DEFAULT 0,

  content_completeness TEXT NOT NULL CHECK (content_completeness IN ('complete','incomplete')),
  missing_fields JSONB NOT NULL DEFAULT '[]'::jsonb,
  input_hash CHAR(64) NOT NULL,
  provenance JSONB NOT NULL DEFAULT '{}'::jsonb,

  UNIQUE (content_run_id, identity_id),
  UNIQUE (content_run_id, seo_slug),
  CHECK (jsonb_typeof(missing_fields)='array'),
  CHECK (jsonb_typeof(verdict_inputs)='object'),
  -- A summary must declare where it came from, and a verdict must name the snapshot it
  -- describes. Neither may float free of its source.
  CHECK ((source_summary IS NULL) = (source_summary_origin IS NULL)),
  CHECK ((jobsvsai_verdict IS NULL) OR (verdict_snapshot_id IS NOT NULL)),
  -- Completeness is a fact about the row, not an opinion the generator may assert.
  CHECK (content_completeness = 'complete'
         OR jsonb_array_length(missing_fields) > 0),
  CHECK (content_completeness = 'incomplete'
         OR (source_summary IS NOT NULL AND jobsvsai_verdict IS NOT NULL
             AND jsonb_array_length(missing_fields) = 0))
);
CREATE INDEX public_content_candidates_run_idx
  ON public_occupation_content_candidates(content_run_id, content_completeness);

CREATE TABLE public_occupation_related_occupations (
  id BIGSERIAL PRIMARY KEY,
  content_run_id BIGINT NOT NULL REFERENCES public_occupation_content_runs(id),
  identity_id BIGINT NOT NULL REFERENCES canonical_occupation_identities(id),
  related_identity_id BIGINT NOT NULL REFERENCES canonical_occupation_identities(id),
  related_onet_soc_code TEXT NOT NULL,
  relatedness_tier TEXT NOT NULL,
  relatedness_rank INTEGER NOT NULL,
  relationship_source TEXT NOT NULL DEFAULT 'onet_related_occupations'
    CHECK (relationship_source = 'onet_related_occupations'),
  UNIQUE (content_run_id, identity_id, related_identity_id),
  CHECK (identity_id <> related_identity_id)
);
CREATE INDEX public_content_related_idx
  ON public_occupation_related_occupations(content_run_id, identity_id, relatedness_rank);

CREATE TRIGGER public_content_runs_append_only
  BEFORE UPDATE OR DELETE ON public_occupation_content_runs
  FOR EACH ROW EXECUTE FUNCTION prevent_ai_enrichment_history_mutation();
CREATE TRIGGER public_content_candidates_append_only
  BEFORE UPDATE OR DELETE ON public_occupation_content_candidates
  FOR EACH ROW EXECUTE FUNCTION prevent_ai_enrichment_history_mutation();
CREATE TRIGGER public_content_related_append_only
  BEFORE UPDATE OR DELETE ON public_occupation_related_occupations
  FOR EACH ROW EXECUTE FUNCTION prevent_ai_enrichment_history_mutation();

COMMENT ON COLUMN public_occupation_content_candidates.source_summary IS
  'The O*NET occupation description, verbatim. Never paraphrased, never model-written.';
COMMENT ON COLUMN public_occupation_content_candidates.jobsvsai_verdict IS
  'JobsVsAI interpretation generated by a versioned template from the named snapshot. '
  'Regenerating it from the same snapshot reproduces the same sentence.';
COMMENT ON TABLE public_occupation_related_occupations IS
  'Adjacency from O*NET, replacing the hand-seeded career_relationships graph for the '
  'launch cohort.';

COMMIT;
